version: '3.3'

services:
  my_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      # 밖인덱스에서 안에있는 인덱스로
      - ./index.js:/myfolder/index.js

  my_database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'myproject'
      MYSQL_PASSWORD: 'root'
    ports:
      - 3306:3306
