version: '3.3'

services:
  my_backend:
    platform: linux/x86_64 # m1 때문에 이거 추가함
    image: asia.gcr.io/codecamp-342701/my_backend:1.2.1
    build:
      context: .
      dockerfile: Dockerfile
    env_file: # cloudbuild.yaml 쓰려면 주석
      - ./.env.prod # cloudbuild.yaml 쓰려면 주석
    # volumes:
    #   - ./src:/my_backend/src
    ports:
      - 3000:3000
  # my_database:
  #   platform: linux/x86_64
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'myproject'
  #     MYSQL_ROOT_PASSWORD: 'root'
  # command:
  #   - --character-set-server=utf8mb4
  #   - --collation-server=utf8mb4_unicode_ci
  #   - --skip-character-set-client-handshake
  # # cap_add:
  # #   - SYS_NICE
  # ports:
  #   - 3306:3306
