version: '3.3'

services:
  my_backend:
    image: asia.gcr.io-codecampproj/my_backend:1.0
    build:
      context: .
      dockerfile: Dockerfile
    env_file: # cloudbuild.yaml 쓰려면 주석
      - ./.env.prod # cloudbuild.yaml 쓰려면 주석
    # volumes:
    #   - ./src:/my_backend/src
    ports:
      - 3000:3000
my_database:
  platform: linux/x86_64
  image: mysql:latest
  environment:
    MYSQL_DATABASE: 'myproject'
    MYSQL_ROOT_PASSWORD: 'root'
# ports:
#   - 3306:3306
